/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        classUnderTest.init(new BigDecimal("11344343141241100.222"));
        classUnderTest.split();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

    }
}
